### ISSUE TITLE
libaircrack

### ISSUE THREAD

**Issue by amxxack66** [pitube08642/aircrack-ng-for-termux#3]
libaircrack-ce-wpa-arm-neon.so not found

**Comment by amxxack66** [comment]
Rename libaircrack-ce-wpa-arm-neon-1.7.0.so to 
 libaircrack-ce-wpa-arm-neon.so

**Comment by Pzkn** [comment]
> Rename libaircrack-ce-wpa-arm-neon-1.7.0.so to libaircrack-ce-wpa-arm-neon.so

How to rename it?

**Comment by ItzNesbroDev** [comment]
> > Rename libaircrack-ce-wpa-arm-neon-1.7.0.so to libaircrack-ce-wpa-arm-neon.so
> 
> How to rename it?

Go to `../usr/lib/` and use `mv libaircrack-ce-wpa-arm-neon-1.7.0.so libaircrack-ce-wpa-arm-neon.so`

**Comment by T31337** [comment]
> > > Rename libaircrack-ce-wpa-arm-neon-1.7.0.so to libaircrack-ce-wpa-arm-neon.so
> > 
> > 
> > How to rename it?
> 
> Go to `../usr/lib/` and use `mv libaircrack-ce-wpa-arm-neon-1.7.0.so libaircrack-ce-wpa-arm-neon.so`

Fixes It For Me, Thank You So Much!

**Comment by rehanmohammed786** [comment]
How to rename it, like the actual process

**Comment by ItzNesbroDev** [comment]
> How to rename it, like the actual process

`cd ../usr/lib/`
`mv libaircrack-ce-wpa-arm-neon-1.7.0.so libaircrack-ce-wpa-arm-neon.so`
