### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by Danen84** [pitube08642/aircrack-ng-for-termux#4]
Every time i wanna update my pkg, its always error because i installed this tool

**Comment by MasterCraft6969** [comment]
Are you trying to upgrade system wide or aircrack?

**Comment by pitube08642** [comment]
> Every time i wanna update my pkg, its always error because i installed this tool


As you may know, Aircrack-ng has been officially delisted from Termux packages.
As a result, it might be unstable on Termux now.
